accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = "accounts"

urlpatterns = [

    url(r'^login/$', login_view, name="login"),

    url(r'^register/$', register_view, name="register"),

    url(r'^logout/$', logout_view, name="logout"),

]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    url(r'^$', home_view, name='home'),

    url(r'^aboutme/', aboutme_view, name='aboutme'),

    url(r'^contactme/', contactme_view, name='contactme'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = "post"

urlpatterns = [

    url(r'^index/$', post_index, name="index"),

    url(r'^create/$', post_create, name='create'),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),

    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name="update"),

    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    if request.user.is_authenticated():
        context = {
            'isim': request.user.username
        }
    else:
        context = {
            'isim': 'Misafir'
        }
    return render(request, 'home.html', context)


def aboutme_view(request):
    if request.user.is_authenticated():
        context = {
            'isim': request.user.username
        }
    else:
        context = {
            'isim': 'Misafir'
        }
    return render(request, 'aboutme.html', context)


def contactme_view(request):
    if request.user.is_authenticated():
        context = {
            'isim': request.user.username
        }
    else:
        context = {
            'isim': 'Misafir'
        }
    return render(request, 'contactme.html', context)

templates/aboutme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Hakkımda - {{ block.super }}
{% endblock %}

{% block body %}

    {# Jumbotron #}
    <div class="jumbotron deneme" style="background-image: url({% static 'img/about-bg.jpg' %});">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-offset-3" style="text-align:center;">
                    <h1>Hakkımda</h1><br>
                    <p>Ben Kimim?</p>
                    {#<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>#}
                </div>
            </div>
        </div>
    </div>
   
    <div class="container-fluid">
        
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% include 'messages.html' %}
                <h1>Ben Kimim?</h1>
                <hr>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis
                    nunc ex, non ultricies massa porttitor ac. Donec vel lectus tellus. Quisque
                    consequat ultrices nulla, et ultrices risus maximus at. Duis imperdiet
                    orci ipsum, vitae ultrices lectus placerat id. Suspendisse id laoreet dolor.
                    Sed pharetra est tempor nulla rhoncus volutpat. Fusce blandit fermentum
                    eros at porta. Cras vestibulum nisi sed nibh eleifend, cursus sollicitudin
                    odio aliquam. Class aptent taciti sociosqu ad litora torquent per conubia
                    nostra, per inceptos himenaeos.
                </p>
    
                <p>
                    Ut eget eros lacinia, convallis arcu nec, fermentum purus. Suspendisse
                    porttitor finibus ligula, quis pulvinar mi consectetur id. Duis at nibh
                    id mauris condimentum faucibus. Vestibulum tellus est, ultrices et purus
                    id, mollis sollicitudin urna. Curabitur semper nunc non varius eleifend.
                    Phasellus aliquam neque nec diam malesuada, sit amet interdum erat
                    consectetur. Vivamus ut fermentum dolor. Aliquam porttitor, sem in
                    dapibus blandit, eros erat fermentum sem, vel vestibulum mauris dolor
                    vel metus. Mauris sagittis tortor eget dui ultricies, gravida ultricies
                    mauris tristique. Proin accumsan nisi vitae tempus scelerisque.
                </p>
    
                <p>
                    In cursus dictum libero, in ullamcorper nisl. Sed malesuada lectus
                    malesuada metus congue blandit. Ut at placerat lorem, quis lacinia
                    libero. Ut accumsan mollis tempus. Praesent vel neque finibus, congue
                    ligula vel, ultrices felis. Ut sed mattis velit. Praesent non augue
                    quis ante auctor euismod. Integer consequat lobortis ligula, eget
                    scelerisque est tempus nec. Cras malesuada nulla in elit pharetra
                    venenatis. Aenean quam nisl, pharetra vel quam eget, vestibulum
                    pulvinar ex.
                <p>
                <hr>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}sonmezmusa{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include "header.html" %}

    {% block body %}

    {% endblock %}

    {% include "footer.html" %}


    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

templates/contactme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

{% block body %}

    {# Jumbotron #}
    <div class="jumbotron deneme" style="background-image: url({% static 'img/contact-bg.jpg' %});">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-offset-3" style="text-align:center;">
                    <h1 >Bana Ulaşın</h1>
                    <p>Merak Mı Ediyorsun?</p>
                    {#<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>#}
                </div>
            </div>
        </div>
    </div>
   
    <div class="container-fluid">
        
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% include 'messages.html' %}
                <h1 style="text-align:right;">İletişim</h1>
                <hr>

                <form class="form-horizontal" action="" method="post">
                <fieldset>
                  <!-- Name input-->
                  <div class="form-group">
                    <label class="col-md-3 control-label" for="name">Adınız</label>
                    <div class="col-md-9">
                      <input id="name" name="name" type="text" placeholder="Adınızı girin" class="form-control">
                    </div>
                  </div>
        
                  <!-- Email input-->
                  <div class="form-group">
                    <label class="col-md-3 control-label" for="email">E-mailiniz</label>
                    <div class="col-md-9">
                      <input id="email" name="email" type="text" placeholder="E-mailinizi girin" class="form-control">
                    </div>
                  </div>
        
                  <!-- Message body -->
                  <div class="form-group">
                    <label class="col-md-3 control-label" for="message">Mesajınız</label>
                    <div class="col-md-9">
                      <textarea class="form-control" id="message" name="message" placeholder="Lütfen mesajınızı buraya yazın..." rows="5"></textarea>
                    </div>
                  </div>
        
                  <!-- Form actions -->
                  <div class="form-group">
                    <div class="col-md-12 text-right">
                      <button type="submit" class="btn btn-primary btn-lg">Gönder</button>
                    </div>
                  </div>
                </fieldset>
                </form>

                <hr>
            </div>
        </div>
    </div>

{% endblock %}

templates/footer.html
<br>
{# Footer #}
<!-- Social Footer, Single Coloured -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->
<div class="text-center center-block footerDiv">
    <br>
    <p class="txt-railway footerP">- sonmezmusa.com -</p>
    <a href="https://www.facebook.com/"><i class="fa fa-facebook-square fa-3x social"></i></a>
	<a href="https://twitter.com/"><i class="fa fa-twitter-square fa-3x social"></i></a>
	<a href="https://plus.google.com/"><i class="fa fa-google-plus-square fa-3x social"></i></a>
	<a href="https://mail.google.com/"><i class="fa fa-envelope-square fa-3x social"></i></a>
    <br><br>
</div>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand" style="font-size:20px;">sonmezmusa</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Postlarda Ara" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}" >Yazı Ekle</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="{% url 'aboutme' %}">Hakkımda</a></li>
                <li><a href="{% url 'contactme' %}">İletişim</a></li>

                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Üye Ol</a></li>
                    <li><a href="{% url 'accounts:login' %}">Giriş</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:logout' %}">Çıkış</a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

{% block body %}

    {# Jumbotron #}
    <div class="jumbotron deneme" style="background-image: url({% static 'img/home-bg.jpg' %});">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-offset-3" style="text-align:center;">
                    <h1 >sonmezmusa.com</h1>
                    <p>Teknoloji, Tasarım, Yazılım</p>
                    {#<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>#}
                </div>
            </div>
        </div>
    </div>
   
    <div class="container-fluid">
        
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% include 'messages.html' %}
                <h1>Hoşgeldin, <b>{{ isim }}</b></h1>
                <hr>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean venenatis
                    nunc ex, non ultricies massa porttitor ac. Donec vel lectus tellus. Quisque
                    consequat ultrices nulla, et ultrices risus maximus at. Duis imperdiet
                    orci ipsum, vitae ultrices lectus placerat id. Suspendisse id laoreet dolor.
                    Sed pharetra est tempor nulla rhoncus volutpat. Fusce blandit fermentum
                    eros at porta. Cras vestibulum nisi sed nibh eleifend, cursus sollicitudin
                    odio aliquam. Class aptent taciti sociosqu ad litora torquent per conubia
                    nostra, per inceptos himenaeos.
                </p>
    
                <p>
                    Ut eget eros lacinia, convallis arcu nec, fermentum purus. Suspendisse
                    porttitor finibus ligula, quis pulvinar mi consectetur id. Duis at nibh
                    id mauris condimentum faucibus. Vestibulum tellus est, ultrices et purus
                    id, mollis sollicitudin urna. Curabitur semper nunc non varius eleifend.
                    Phasellus aliquam neque nec diam malesuada, sit amet interdum erat
                    consectetur. Vivamus ut fermentum dolor. Aliquam porttitor, sem in
                    dapibus blandit, eros erat fermentum sem, vel vestibulum mauris dolor
                    vel metus. Mauris sagittis tortor eget dui ultricies, gravida ultricies
                    mauris tristique. Proin accumsan nisi vitae tempus scelerisque.
                </p>
    
                <p>
                    In cursus dictum libero, in ullamcorper nisl. Sed malesuada lectus
                    malesuada metus congue blandit. Ut at placerat lorem, quis lacinia
                    libero. Ut accumsan mollis tempus. Praesent vel neque finibus, congue
                    ligula vel, ultrices felis. Ut sed mattis velit. Praesent non augue
                    quis ante auctor euismod. Integer consequat lobortis ligula, eget
                    scelerisque est tempus nec. Cras malesuada nulla in elit pharetra
                    venenatis. Aenean quam nisl, pharetra vel quam eget, vestibulum
                    pulvinar ex.
                <p>
                <hr>
            </div>
        </div>
    </div>

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}